@baseURL = http://localhost:3000/v1

# User
@register = register
@login = login

# POST /register
POST {{baseURL}}/{{register}}
Content-Type: application/json

{

}

###

# POST /login
POST {{baseURL}}/{{login}}
Content-Type: application/json

{

}

###

# Department
@depart = department
@departs = departments

###
POST {{baseURL}}/{{depart}}
Content-Type: application/json

{

}

###
PUT {{baseURL}}/{{depart}}/{id}
Content-Type: application/json

{

}

###
DELETE {{baseURL}}/{{depart}}/{id}
Content-Type: application/json

{

}

###
GET {{baseURL}}/{{depart}}/{id}

###
GET {{baseURL}}/{{departs}}

###

# Comment
@com = comment
@coms = comments

POST {{baseURL}}/{{com}}
Content-Type: application/json

{

}

###
PATCH {{baseURL}}/{{com}}/{id}
Content-Type: application/json

{

}

###
DELETE {{baseURL}}/{{com}}/{id}
Content-Type: application/json

{

}

###
GET {{baseURL}}/{{com}}/{id}

###
GET {{baseURL}}/{{coms}}

###

# Idea
@i = idea
@is = ideas

POST {{baseURL}}/{{i}}/{id}/role 
Content-Type: application/json

{

}

###
PATCH {{baseURL}}/{{i}}/{id}
Content-Type: application/json

{

}

###
DELETE {{baseURL}}/{{i}}/{id}
Content-Type: application/json

{

}

###
GET {{baseURL}}/{{i}}/{id}

###
GET {{baseURL}}/{{is}}

###

# Submission
@submit = submission
@submits = submissions

POST {{baseURL}}/{{submit}}
Content-Type: application/json

{

}

###
PATCH {{baseURL}}/{{submit}}/{id}
Content-Type: application/json

{

}

###
DELETE {{baseURL}}/{{submit}}/{id}
Content-Type: application/json

{

}

###
GET {{baseURL}}/{{submit}}/{id}

###
GET {{baseURL}}/{{submits}}

###

# View
POST {{baseURL}}/view
Content-Type: application/json

{

}

###

# Category
@cate = category
@cates = categories

POST {{baseURL}}/{{cate}}
Content-Type: application/json

{
    
}
###

# Role
@role = role
@roles = roles

###

# Reaction Submit
@rsb = react-submit
@rsbs = react-submits


